name: MocaPass
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.1
  flutter_bloc: ^8.1.6
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  gap: ^3.0.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  http: ^1.2.0
  json_annotation: ^4.8.1
  liquid_pull_to_refresh: ^3.0.1
  logger: ^2.0.2+1
  responsive_builder: ^0.7.0
  svg_flutter: ^0.0.1
  flutter_native_splash: ^2.4.1
#  ai_barcode_scanner: ^6.0.1
  loader_overlay: ^4.0.4+1
#  mobile_scanner: ^6.0.6
  permission_handler: ^11.4.0
  camera: ^0.10.5+5
  google_mlkit_barcode_scanning: ^0.13.0

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#9A28CD"
  background_image: "assets/images/splash.png"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  image: assets/images/app_icon.png
  android_12:
    image: assets/images/app_icon.png
  branding_mode: center

flutter_app_name:
  name: "Moca Pass"

dev_dependencies:
#  very_good_analysis: ^6.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GTWalsheimPro
      fonts:
        - asset: assets/fonts/GTWalsheimProLight.ttf
          weight: 300
        - asset: assets/fonts/GTWalsheimProRegular.ttf
          weight: 400
        - asset: assets/fonts/GTWalsheimProMedium.ttf
          weight: 500
        - asset: assets/fonts/GTWalsheimProBold.ttf
          weight: 600
        - asset: assets/fonts/GTWalsheimProBold.ttf
          weight: 700
        - asset: assets/fonts/GTWalsheimProUltraBoldOblique.ttf
          weight: 800